### ISSUE TITLE
`prox new` allows creation of duplicate container

### ISSUE THREAD

**Issue by atombaby** [FredHutch/proxmox-tools#1]
To reproduce, create container "foo":

`prox new foo`

When complete, repeat the command:

`prox new foo`

A new container will be created with a new container ID, IP address, but will have the same hostname and container name.  Interestingly, the DNS does not seem to get updated with the new container's IP.

**Comment by dirkpetersen** [comment]
fixed...added hostdedupe 

prox new drill125 testitest

host drill125 already exits, removing from list
installing container on node "proxa1" !!! 
creating host testitest with ID 159 in pool SciComp
    ...UPID:proxa1:00007DF0:1422CC8D:581F7CEF:vzcreate:159:petersen@FHCRC.ORG:
Starting host 159 ..
