### ISSUE TITLE
Enable snapshots from prox

### ISSUE THREAD

**Issue by atombaby** [FredHutch/proxmox-tools#2]
A `prox snap <container>` sub-command that creates a snapshot of the indicated container at the current point in time.

**Comment by dirkpetersen** [comment]
this is now ready

> prox snap --help
> usage: prox snap [-h] [--description SNAPDESC] snapname [hosts [hosts ...]]

positional arguments:
  snapname              name of the snapshot
  hosts                 hostname(s) of VM/containers (separated by space),
                        example: prox snap host1 host2 host3

optional arguments:
  -h, --help            show this help message and exit
  --description SNAPDESC, -d SNAPDESC
                        description of the snapshot

> prox rb --help
> usage: prox rollback [-h] snapname [hosts [hosts ...]]

positional arguments:
  snapname    name of the snapshot
  hosts       hostname(s) of VM/containers (separated by space), example: prox
              snap host1 host2 host3

optional arguments:
  -h, --help  show this help message and exit

> prox list --help
> usage: prox list [-h] [--all] [--contacts] [--snapshots] [hosts [hosts ...]]

positional arguments:
  hosts            hostname(s) of VM/containers (separated by space), example:
                   prox modify host1 host2 host3

optional arguments:
  -h, --help       show this help message and exit
  --all, -a        show all hosts (LXC and KVM)
  --contacts, -c   show the technical contact / owner of the machine
  --snapshots, -s  list machine snapshots that can be rolled back
